#!/bin/bash

logfile=./logs/pytest.log
timestamp="$(date '+%Y-%m-%d %H:%M:%S') ============================================================"
echo -e "\n\n$timestamp" >> "$logfile"
pytest | tee -a >(sed -r "s/\x1B\[[0-9;]*[mK]//g" >> ./logs/pytest.log)
