#!/bin/bash

logfile=./logs/pytest.log
timestamp="$(date '+%Y-%m-%d %H:%M:%S') ============================================================"
echo -e "\n\n$timestamp" >> "$logfile"
echo "===== PARALLEL TESTS ====="
pytest -n auto -m "not serial" | tee -a >(sed -r "s/\x1B\[[0-9;]*[mK]//g" >> "$logfile")
# echo; echo; echo "===== SERIAL TESTS ====="
# pytest -n 1 -m "serial" | tee -a >(sed -r "s/\x1B\[[0-9;]*[mK]//g" >> "$logfile")
